from typing import Any

from external import DataSource
from schemas.countries import CountryInfo

COUNTRY_ALREADY_IN_DB = CountryInfo(
    code="AID",
    name="Country already in DB",
    capital="INIT",
    population=42,
)


class RestcountriesMockDataSource(DataSource):
    async def get_data(self) -> Any:
        return [
            {
                "name": {
                    "common": "France",
                    "official": "French Republic",
                    "nativeName": {
                        "fra": {"official": "République française", "common": "France"}
                    },
                },
                "tld": [".fr"],
                "cca2": "FR",
                "ccn3": "250",
                "cca3": "FRA",
                "cioc": "FRA",
                "independent": True,
                "status": "officially-assigned",
                "unMember": True,
                "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
                "idd": {"root": "+3", "suffixes": ["3"]},
                "capital": ["Paris"],
                "altSpellings": ["FR", "French Republic", "République française"],
                "region": "Europe",
                "subregion": "Western Europe",
                "languages": {"fra": "French"},
                "translations": {
                    "ara": {"official": "الجمهورية الفرنسية", "common": "فرنسا"},
                    "bre": {"official": "Republik Frañs", "common": "Frañs"},
                    "ces": {"official": "Francouzská republika", "common": "Francie"},
                    "cym": {"official": "French Republic", "common": "France"},
                    "deu": {
                        "official": "Französische Republik",
                        "common": "Frankreich",
                    },
                    "est": {"official": "Prantsuse Vabariik", "common": "Prantsusmaa"},
                    "fin": {"official": "Ranskan tasavalta", "common": "Ranska"},
                    "fra": {"official": "République française", "common": "France"},
                    "hrv": {"official": "Francuska Republika", "common": "Francuska"},
                    "hun": {
                        "official": "Francia Köztársaság",
                        "common": "Franciaország",
                    },
                    "ita": {"official": "Repubblica francese", "common": "Francia"},
                    "jpn": {"official": "フランス共和国", "common": "フランス"},
                    "kor": {"official": "프랑스 공화국", "common": "프랑스"},
                    "nld": {"official": "Franse Republiek", "common": "Frankrijk"},
                    "per": {"official": "جمهوری فرانسه", "common": "فرانسه"},
                    "pol": {"official": "Republika Francuska", "common": "Francja"},
                    "por": {"official": "República Francesa", "common": "França"},
                    "rus": {"official": "Французская Республика", "common": "Франция"},
                    "slk": {"official": "Francúzska republika", "common": "Francúzsko"},
                    "spa": {"official": "República francés", "common": "Francia"},
                    "srp": {"official": "Француска Република", "common": "Француска"},
                    "swe": {"official": "Republiken Frankrike", "common": "Frankrike"},
                    "tur": {"official": "Fransa Cumhuriyeti", "common": "Fransa"},
                    "urd": {"official": "جمہوریہ فرانس", "common": "فرانس"},
                    "zho": {"official": "法兰西共和国", "common": "法国"},
                },
                "latlng": [46.0, 2.0],
                "landlocked": False,
                "borders": ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
                "area": 551695.0,
                "demonyms": {
                    "eng": {"f": "French", "m": "French"},
                    "fra": {"f": "Française", "m": "Français"},
                },
                "flag": "🇫🇷",
                "maps": {
                    "googleMaps": "https://goo.gl/maps/g7QxxSFsWyTPKuzd7",
                    "openStreetMaps": "https://www.openstreetmap.org/relation/1403916",
                },
                "population": 67391582,
                "gini": {"2018": 32.4},
                "fifa": "FRA",
                "car": {"signs": ["F"], "side": "right"},
                "timezones": [
                    "UTC-10:00",
                    "UTC-09:30",
                    "UTC-09:00",
                    "UTC-08:00",
                    "UTC-04:00",
                    "UTC-03:00",
                    "UTC+01:00",
                    "UTC+02:00",
                    "UTC+03:00",
                    "UTC+04:00",
                    "UTC+05:00",
                    "UTC+10:00",
                    "UTC+11:00",
                    "UTC+12:00",
                ],
                "continents": ["Europe"],
                "flags": {
                    "png": "https://flagcdn.com/w320/fr.png",
                    "svg": "https://flagcdn.com/fr.svg",
                    "alt": "The flag of France is composed of three equal vertical bands of blue, white and red.",
                },
                "coatOfArms": {
                    "png": "https://mainfacts.com/media/images/coats_of_arms/fr.png",
                    "svg": "https://mainfacts.com/media/images/coats_of_arms/fr.svg",
                },
                "startOfWeek": "monday",
                "capitalInfo": {"latlng": [48.87, 2.33]},
                "postalCode": {"format": "#####", "regex": "^(\\d{5})$"},
            },
            {
                "name": {
                    "common": "Germany",
                    "official": "Federal Republic of Germany",
                    "nativeName": {
                        "deu": {
                            "official": "Bundesrepublik Deutschland",
                            "common": "Deutschland",
                        }
                    },
                },
                "tld": [".de"],
                "cca2": "DE",
                "ccn3": "276",
                "cca3": "DEU",
                "cioc": "GER",
                "independent": True,
                "status": "officially-assigned",
                "unMember": True,
                "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
                "idd": {"root": "+4", "suffixes": ["9"]},
                "capital": ["Berlin"],
                "altSpellings": [
                    "DE",
                    "Federal Republic of Germany",
                    "Bundesrepublik Deutschland",
                ],
                "region": "Europe",
                "subregion": "Western Europe",
                "languages": {"deu": "German"},
                "translations": {
                    "ara": {
                        "official": "جمهورية ألمانيا الاتحادية",
                        "common": "ألمانيا",
                    },
                    "bre": {
                        "official": "Republik Kevreadel Alamagn",
                        "common": "Alamagn",
                    },
                    "ces": {
                        "official": "Spolková republika Německo",
                        "common": "Německo",
                    },
                    "cym": {
                        "official": "Federal Republic of Germany",
                        "common": "Germany",
                    },
                    "deu": {
                        "official": "Bundesrepublik Deutschland",
                        "common": "Deutschland",
                    },
                    "est": {"official": "Saksamaa Liitvabariik", "common": "Saksamaa"},
                    "fin": {"official": "Saksan liittotasavalta", "common": "Saksa"},
                    "fra": {
                        "official": "République fédérale d'Allemagne",
                        "common": "Allemagne",
                    },
                    "hrv": {
                        "official": "Njemačka Federativna Republika",
                        "common": "Njemačka",
                    },
                    "hun": {
                        "official": "Német Szövetségi Köztársaság",
                        "common": "Németország",
                    },
                    "ita": {
                        "official": "Repubblica federale di Germania",
                        "common": "Germania",
                    },
                    "jpn": {"official": "ドイツ連邦共和国", "common": "ドイツ"},
                    "kor": {"official": "독일 연방 공화국", "common": "독일"},
                    "nld": {
                        "official": "Bondsrepubliek Duitsland",
                        "common": "Duitsland",
                    },
                    "per": {"official": "جمهوری فدرال آلمان", "common": "آلمان"},
                    "pol": {
                        "official": "Republika Federalna Niemiec",
                        "common": "Niemcy",
                    },
                    "por": {
                        "official": "República Federal da Alemanha",
                        "common": "Alemanha",
                    },
                    "rus": {
                        "official": "Федеративная Республика Германия",
                        "common": "Германия",
                    },
                    "slk": {
                        "official": "Nemecká spolková republika",
                        "common": "Nemecko",
                    },
                    "spa": {
                        "official": "República Federal de Alemania",
                        "common": "Alemania",
                    },
                    "srp": {
                        "official": "Савезна Република Немачка",
                        "common": "Немачка",
                    },
                    "swe": {
                        "official": "Förbundsrepubliken Tyskland",
                        "common": "Tyskland",
                    },
                    "tur": {
                        "official": "Almanya Federal Cumhuriyeti",
                        "common": "Almanya",
                    },
                    "urd": {"official": "وفاقی جمہوریہ جرمنی", "common": "جرمنی"},
                    "zho": {"official": "德意志联邦共和国", "common": "德国"},
                },
                "latlng": [51.0, 9.0],
                "landlocked": False,
                "borders": [
                    "AUT",
                    "BEL",
                    "CZE",
                    "DNK",
                    "FRA",
                    "LUX",
                    "NLD",
                    "POL",
                    "CHE",
                ],
                "area": 357114.0,
                "demonyms": {
                    "eng": {"f": "German", "m": "German"},
                    "fra": {"f": "Allemande", "m": "Allemand"},
                },
                "flag": "🇩🇪",
                "maps": {
                    "googleMaps": "https://goo.gl/maps/mD9FBMq1nvXUBrkv6",
                    "openStreetMaps": "https://www.openstreetmap.org/relation/51477",
                },
                "population": 83240525,
                "gini": {"2016": 31.9},
                "fifa": "GER",
                "car": {"signs": ["DY"], "side": "right"},
                "timezones": ["UTC+01:00"],
                "continents": ["Europe"],
                "flags": {
                    "png": "https://flagcdn.com/w320/de.png",
                    "svg": "https://flagcdn.com/de.svg",
                    "alt": "The flag of Germany is composed of three equal horizontal bands of black, red and gold.",
                },
                "coatOfArms": {
                    "png": "https://mainfacts.com/media/images/coats_of_arms/de.png",
                    "svg": "https://mainfacts.com/media/images/coats_of_arms/de.svg",
                },
                "startOfWeek": "monday",
                "capitalInfo": {"latlng": [52.52, 13.4]},
                "postalCode": {"format": "#####", "regex": "^(\\d{5})$"},
            },
            {
                "name": {
                    "common": "Switzerland",
                    "official": "Swiss Confederation",
                    "nativeName": {
                        "fra": {"official": "Confédération suisse", "common": "Suisse"},
                        "gsw": {
                            "official": "Schweizerische Eidgenossenschaft",
                            "common": "Schweiz",
                        },
                        "ita": {
                            "official": "Confederazione Svizzera",
                            "common": "Svizzera",
                        },
                        "roh": {"official": "Confederaziun svizra", "common": "Svizra"},
                    },
                },
                "tld": [".ch"],
                "cca2": "CH",
                "ccn3": "756",
                "cca3": "CHE",
                "cioc": "SUI",
                "independent": True,
                "status": "officially-assigned",
                "unMember": True,
                "currencies": {"CHF": {"name": "Swiss franc", "symbol": "Fr."}},
                "idd": {"root": "+4", "suffixes": ["1"]},
                "capital": ["Bern"],
                "altSpellings": [
                    "CH",
                    "Swiss Confederation",
                    "Schweiz",
                    "Suisse",
                    "Svizzera",
                    "Svizra",
                ],
                "region": "Europe",
                "subregion": "Western Europe",
                "languages": {
                    "fra": "French",
                    "gsw": "Swiss German",
                    "ita": "Italian",
                    "roh": "Romansh",
                },
                "translations": {
                    "ara": {"official": "الاتحاد السويسري", "common": "سويسرا"},
                    "bre": {"official": "Kengevredad Suis", "common": "Suis"},
                    "ces": {"official": "Švýcarská konfederace", "common": "Švýcarsko"},
                    "cym": {"official": "Swiss Confederation", "common": "Switzerland"},
                    "deu": {
                        "official": "Schweizerische Eidgenossenschaft",
                        "common": "Schweiz",
                    },
                    "est": {"official": "Šveitsi Konföderatsioon", "common": "Šveits"},
                    "fin": {"official": "Sveitsin valaliitto", "common": "Sveitsi"},
                    "fra": {"official": "Confédération suisse", "common": "Suisse"},
                    "hrv": {
                        "official": "švicarska Konfederacija",
                        "common": "Švicarska",
                    },
                    "hun": {"official": "Svájc", "common": "Svájc"},
                    "ita": {
                        "official": "Confederazione svizzera",
                        "common": "Svizzera",
                    },
                    "jpn": {"official": "スイス連邦", "common": "スイス"},
                    "kor": {"official": "스위스 연방", "common": "스위스"},
                    "nld": {
                        "official": "Zwitserse Confederatie",
                        "common": "Zwitserland",
                    },
                    "per": {"official": "کنفدراسیون سوئیس", "common": "سوئیس"},
                    "pol": {
                        "official": "Konfederacja Szwajcarska",
                        "common": "Szwajcaria",
                    },
                    "por": {"official": "Confederação Suíça", "common": "Suíça"},
                    "rus": {
                        "official": "Швейцарская Конфедерация",
                        "common": "Швейцария",
                    },
                    "slk": {
                        "official": "Švajčiarska konfederácia",
                        "common": "Švajčiarsko",
                    },
                    "spa": {"official": "Confederación Suiza", "common": "Suiza"},
                    "srp": {
                        "official": "Швајцарска Конфедерација",
                        "common": "Швајцарска",
                    },
                    "swe": {
                        "official": "Schweiziska edsförbundet",
                        "common": "Schweiz",
                    },
                    "tur": {"official": "İsviçre Konfederasyonu", "common": "İsviçre"},
                    "urd": {"official": "سوئیس  متحدہ", "common": "سویٹذرلینڈ"},
                    "zho": {"official": "瑞士联邦", "common": "瑞士"},
                },
                "latlng": [47.0, 8.0],
                "landlocked": True,
                "borders": ["AUT", "FRA", "ITA", "LIE", "DEU"],
                "area": 41284.0,
                "demonyms": {
                    "eng": {"f": "Swiss", "m": "Swiss"},
                    "fra": {"f": "Suisse", "m": "Suisse"},
                },
                "flag": "🇨🇭",
                "maps": {
                    "googleMaps": "https://goo.gl/maps/uVuZcXaxSx5jLyEC9",
                    "openStreetMaps": "https://www.openstreetmap.org/relation/51701",
                },
                "population": 8654622,
                "gini": {"2018": 33.1},
                "fifa": "SUI",
                "car": {"signs": ["CH"], "side": "right"},
                "timezones": ["UTC+01:00"],
                "continents": ["Europe"],
                "flags": {
                    "png": "https://flagcdn.com/w320/ch.png",
                    "svg": "https://flagcdn.com/ch.svg",
                    "alt": "The flag of Switzerland is square shaped. It features a white Swiss cross centered on a red field.",
                },
                "coatOfArms": {
                    "png": "https://mainfacts.com/media/images/coats_of_arms/ch.png",
                    "svg": "https://mainfacts.com/media/images/coats_of_arms/ch.svg",
                },
                "startOfWeek": "monday",
                "capitalInfo": {"latlng": [46.92, 7.47]},
                "postalCode": {"format": "####", "regex": "^(\\d{4})$"},
            },
        ]
